name: rechentrainer

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ cms ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Cache Dependencies
        id: flutter-cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: flutter
          key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}-${{ hashFiles('code/pubspec.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}-
            ${{ env.cache-name }}-ubuntu-latest-
            ${{ env.cache-name }}-

      - name: Dependencies
        run: |
          flutter pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Tests
        run: flutter test --coverage

      - name: Code Coverage HTML artifact
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: summarize Code Coverage
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines......: | cut -f2 -d ':' | cut -f1 -d '(')
          echo "COVERAGE=$(echo $COVERAGE)" >> $GITHUB_ENV

      - name: Create Code Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: rechentrainer.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: green

  build:
    name: Build & Deploy
    needs: [test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Cache Dependencies
        id: flutter-cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: flutter
          key: ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}-${{ hashFiles('code/pubspec.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-ubuntu-latest-${{ steps.get-flutter-version.outputs.version }}-
            ${{ env.cache-name }}-ubuntu-latest-
            ${{ env.cache-name }}-

      - name: Dependencies
        run: |
          flutter pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build
        run: |
          flutter pub run flutter_launcher_icons:main
          flutter build apk
          flutter build web --base-href "/rechentrainer/"

      - name: Archive Builds
        uses: actions/upload-artifact@v2
        with:
          name: Android
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/web
