name: rechentrainer

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ cms ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Dependencies
        run: |
          flutter pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Tests
        run: flutter test

  build:
    name: Build & Deploy
    needs: [test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      - name: Dependencies
        run: |
          flutter pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build
        run: |
          flutter build apk
          flutter build web --base-href "/rechentrainer/"

      - name: Archive Builds
        uses: actions/upload-artifact@v2
        with:
          name: Android
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/web
